// <auto-generated />
using System;
using BatmanCoop.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BatmanCoop.Migrations
{
    [DbContext(typeof(DataBaseConfiguration))]
    partial class DataBaseConfigurationModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BatmanCoopShared.Model.AccountModel.UserAccountM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Acc_Status")
                        .HasColumnType("bit");

                    b.Property<string>("Account_Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count_Update")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_Create")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Expire")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date_Renew")
                        .HasColumnType("datetime2");

                    b.Property<string>("Def_Pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemMId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reg_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemMId");

                    b.ToTable("UserAccountTable");
                });

            modelBuilder.Entity("BatmanCoopShared.Model.LendModel.BuyerDetailsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Approve_Status")
                        .HasColumnType("datetime2");

                    b.Property<int>("BuyMId")
                        .HasColumnType("int");

                    b.Property<int>("Buy_Count")
                        .HasColumnType("int");

                    b.Property<string>("Buy_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemMId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Points_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reference_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Share_Capital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Share_Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyMId");

                    b.HasIndex("MemMId");

                    b.ToTable("BuyerDetailsTable");
                });

            modelBuilder.Entity("BatmanCoopShared.Model.LendModel.BuyerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Buy_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Share_Capital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Share_Points")
                        .HasColumnType("int");

                    b.Property<string>("Share_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Valid_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BuyerTable");
                });

            modelBuilder.Entity("BatmanCoopShared.Model.LogsModel.TransactionLogsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyMId")
                        .HasColumnType("int");

                    b.Property<decimal>("Buy_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemMId")
                        .HasColumnType("int");

                    b.Property<string>("Payment_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trans_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trans_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuyMId");

                    b.HasIndex("MemMId");

                    b.ToTable("TransLogsTable");
                });

            modelBuilder.Entity("BatmanCoopShared.Model.ManpowerModel.MemberAttachM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Img_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img_Contenttype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Img_Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("Img_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Img_Filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img_URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Member_No")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MemAttachTable");
                });

            modelBuilder.Entity("BatmanCoopShared.Model.ManpowerModel.MemberM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Bank_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("CivilStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAdd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PayTypeMId")
                        .HasColumnType("int");

                    b.Property<string>("ReferralId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferralName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PayTypeMId");

                    b.ToTable("MemberTable");
                });

            modelBuilder.Entity("BatmanCoopShared.Model.MasterDataModel.CivilStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CivilStatusTable");
                });

            modelBuilder.Entity("BatmanCoopShared.Model.MasterDataModel.PaymentTypeM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentTypeTable");
                });

            modelBuilder.Entity("BatmanCoopShared.Model.AccountModel.UserAccountM", b =>
                {
                    b.HasOne("BatmanCoopShared.Model.ManpowerModel.MemberM", "MemM")
                        .WithMany()
                        .HasForeignKey("MemMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemM");
                });

            modelBuilder.Entity("BatmanCoopShared.Model.LendModel.BuyerDetailsModel", b =>
                {
                    b.HasOne("BatmanCoopShared.Model.LendModel.BuyerModel", "BuyM")
                        .WithMany()
                        .HasForeignKey("BuyMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BatmanCoopShared.Model.ManpowerModel.MemberM", "MemM")
                        .WithMany()
                        .HasForeignKey("MemMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyM");

                    b.Navigation("MemM");
                });

            modelBuilder.Entity("BatmanCoopShared.Model.LogsModel.TransactionLogsModel", b =>
                {
                    b.HasOne("BatmanCoopShared.Model.LendModel.BuyerModel", "BuyM")
                        .WithMany()
                        .HasForeignKey("BuyMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BatmanCoopShared.Model.ManpowerModel.MemberM", "MemM")
                        .WithMany()
                        .HasForeignKey("MemMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyM");

                    b.Navigation("MemM");
                });

            modelBuilder.Entity("BatmanCoopShared.Model.ManpowerModel.MemberM", b =>
                {
                    b.HasOne("BatmanCoopShared.Model.MasterDataModel.PaymentTypeM", "PayTypeM")
                        .WithMany()
                        .HasForeignKey("PayTypeMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayTypeM");
                });
#pragma warning restore 612, 618
        }
    }
}
